# Generated by Django 3.2.6 on 2022-12-13 11:22

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_modificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=12)),
                ('direccion', models.CharField(max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Clientes',
                'ordering': ['last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='data_chip',
            fields=[
                ('id_chip', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_chip', models.CharField(max_length=12)),
                ('ubicacion_chip', models.CharField(max_length=50)),
                ('nombre_local_chip', models.CharField(max_length=50)),
                ('fecha_reg_chip', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 6, 22, 50, 79927))),
                ('user_chip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data de Chip',
                'verbose_name_plural': 'Registro de CIs',
                'db_table': 'data_Chip',
                'ordering': ['id_chip'],
            },
        ),
        migrations.CreateModel(
            name='data_reg',
            fields=[
                ('id_data', models.BigAutoField(primary_key=True, serialize=False)),
                ('tem_ambiente', models.FloatField()),
                ('tem_objeto', models.FloatField()),
                ('cuenta_in', models.IntegerField()),
                ('cuenta_out', models.IntegerField()),
                ('crc', models.IntegerField()),
                ('topic_sub', models.CharField(max_length=25)),
                ('evento', models.CharField(max_length=25)),
                ('fecha_data', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 6, 22, 50, 79927))),
                ('codigo_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineapp.data_chip')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'Registro de Data',
                'db_table': 'data_reg',
                'ordering': ['id_data'],
            },
        ),
    ]
