# Generated by Django 3.2.6 on 2022-12-13 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0002_auto_20221213_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_chip',
            name='fecha_reg_chip',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 6, 31, 26, 668168)),
        ),
        migrations.AlterField(
            model_name='data_reg',
            name='fecha_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 6, 31, 26, 668168)),
        ),
    ]
