# Generated by Django 5.2.8 on 2025-12-03 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0003_auto_20221213_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_chip',
            name='fecha_reg_chip',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 21, 21, 20, 726517)),
        ),
        migrations.AlterField(
            model_name='data_reg',
            name='fecha_data',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 21, 21, 20, 726717)),
        ),
    ]
