# Generated by Django 5.2.9 on 2025-12-03 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_alter_data_chip_fecha_reg_chip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_chip',
            name='fecha_reg_chip',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 21, 57, 1, 555909)),
        ),
        migrations.AlterField(
            model_name='data_reg',
            name='fecha_data',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 21, 57, 1, 556099)),
        ),
    ]
